#!/usr/bin/python
import sys
import os

def main():
    try:
        #check if in development dir:
        devdir = os.path.join(os.getcwd(), "src")
        if os.path.exists(devdir):
            sys.path.append(devdir)
    
        from pythm import startPythm
        startPythm()
    except NameError,e:
        print "could not find pythm: "+str(e)

if __name__ == "__main__":
    main()
