#!/usr/bin/python
import sys
import os
import traceback

def main():
    try:
        from pythm import startPythm
        startPythm()
    except NameError,e:
        traceback.print_exc()

if __name__ == "__main__":
    main()
