#!/usr/bin/python
import sys
import os

def main():
    try:
        from pythm import startPythm
        startPythm()
    except NameError,e:
        print "could not find pythm: "+str(e)

if __name__ == "__main__":
    main()
